### ISSUE TITLE
ILMerge system.Reactive and rewrite namespaces

### ISSUE THREAD

**Issue by SeanFarrow** [Mpdreamz/elasticsearch-net-abstraction#2]
We need to ILMerge the System.Reactive assembly and rewrite any namespaces that clash.
This is to allow us to have a base library with no dependencies.

**Comment by Mpdreamz** [comment]
@SeanFarrow took some doing but this now lives over here:

https://github.com/proc-net/proc

I just published the first version of it on `nuget.org`:

https://www.nuget.org/packages/Proc

Its dependency free due to merging and rewriting internalized namespaces (`System.Reactive.*``).

Next up removing it from this repos and focussing on `ElasticsearchNode`

**Comment by SeanFarrow** [comment]
@mpdreamz, Let me know how best I can help. I’ve got some time to spend on this if needed.
